import { Workout } from './types';

export const fallbackWorkouts: Workout[] = [
  { id:'1', name:'Barbell Bench Press', category:['Chest','Arms'], equipment:'Barbell, Bench', duration:25, calories:180, rating:4.8, difficulty:'Intermediate', sets:4, reps:'6-8', description:'A compound press that builds chest thickness, triceps, and pressing power from a stable bench.', instructions:['Set your eyes under the bar and grip just outside shoulder width.','Unrack the bar and lower it with control toward your mid-chest.','Press through your palms until your arms are straight.','Rack the bar safely, keeping your shoulders pinned down.'] },
  { id:'2', name:'Goblet Squat', category:['Legs','Core'], equipment:'Kettlebell', duration:20, calories:150, rating:4.7, difficulty:'Beginner', sets:4, reps:'10-12', description:'A front-loaded squat that builds strong legs while teaching excellent squat mechanics.', instructions:['Hold the kettlebell close to your chest.','Brace your core and sit down between your hips.','Drive through your whole foot to stand tall.','Keep your chest proud through every repetition.'] },
  { id:'3', name:'Russian Twist', category:['Core'], equipment:'Medicine Ball', duration:15, calories:120, rating:4.6, difficulty:'Intermediate', sets:3, reps:'16-20', description:'A rotational core movement for control, balance, and athletic trunk strength.', instructions:['Sit with knees bent and lean back slightly.','Hold the ball with both hands at chest height.','Rotate your torso from side to side.','Keep your hips still and move with control.'] },
  { id:'4', name:'Romanian Deadlift', category:['Legs','Back'], equipment:'Dumbbells', duration:30, calories:230, rating:4.9, difficulty:'Intermediate', sets:4, reps:'8-10', description:'A deliberate hip hinge for powerful hamstrings and resilient glutes.', instructions:['Stand tall with weights by your thighs.','Push your hips back while keeping a soft knee bend.','Lower until you feel tension through your hamstrings.','Squeeze your glutes to return to standing.'] },
  { id:'5', name:'Pull-Up', category:['Back','Arms'], equipment:'Pull-up Bar', duration:18, calories:160, rating:4.8, difficulty:'Advanced', sets:4, reps:'5-8', description:'The classic bodyweight pull for a wide, strong, capable back.', instructions:['Grip the bar just outside shoulder width.','Start from a controlled dead hang.','Pull your elbows down toward your ribs.','Lower slowly until your arms are straight.'] },
  { id:'6', name:'Overhead Press', category:['Shoulders','Arms'], equipment:'Barbell', duration:22, calories:170, rating:4.7, difficulty:'Intermediate', sets:4, reps:'6-8', description:'A standing press that builds durable shoulders and total-body stability.', instructions:['Rack the bar at your upper chest.','Brace your ribs down and squeeze your glutes.','Press the bar overhead in a straight line.','Lower it back to your shoulders with control.'] },
  { id:'7', name:'Dumbbell Row', category:['Back','Arms'], equipment:'Dumbbells, Bench', duration:20, calories:145, rating:4.6, difficulty:'Beginner', sets:3, reps:'10-12', description:'A supported pull that adds back density and clean shoulder movement.', instructions:['Place one hand and knee on a bench.','Let the dumbbell hang below your shoulder.','Pull your elbow toward your hip.','Lower the weight without twisting your torso.'] },
  { id:'8', name:'Walking Lunge', category:['Legs'], equipment:'Dumbbells', duration:24, calories:190, rating:4.7, difficulty:'Beginner', sets:3, reps:'12 each', description:'A moving single-leg challenge for balance, strength, and conditioning.', instructions:['Stand tall with a dumbbell in each hand.','Step forward and lower your back knee.','Push off the front foot to bring your feet together.','Alternate sides while keeping your torso upright.'] },
  { id:'9', name:'Cable Fly', category:['Chest'], equipment:'Cable Machine', duration:18, calories:125, rating:4.5, difficulty:'Beginner', sets:3, reps:'12-15', description:'A focused chest squeeze that keeps tension where you need it.', instructions:['Set the handles just above shoulder height.','Step forward with a soft bend in your elbows.','Sweep your hands together in front of your chest.','Return slowly until you feel a full stretch.'] },
  { id:'10', name:'Plank', category:['Core'], equipment:'Bodyweight', duration:10, calories:80, rating:4.4, difficulty:'Beginner', sets:3, reps:'45 sec', description:'A simple, honest brace that teaches your whole body to hold strong.', instructions:['Place elbows beneath your shoulders.','Extend your legs and brace your midsection.','Keep your hips level with your shoulders.','Breathe steadily and hold with perfect form.'] },
  { id:'11', name:'Bicep Curl', category:['Arms'], equipment:'Dumbbells', duration:15, calories:100, rating:4.5, difficulty:'Beginner', sets:3, reps:'10-12', description:'A strict arm builder that rewards control over momentum.', instructions:['Stand tall with palms facing forward.','Curl the weights without moving your elbows.','Squeeze briefly at the top.','Lower for a slow three-count.'] },
  { id:'12', name:'Hip Thrust', category:['Legs','Glutes'], equipment:'Barbell, Bench', duration:25, calories:200, rating:4.8, difficulty:'Intermediate', sets:4, reps:'8-12', description:'A powerful glute-focused lift for hip drive and lower-body strength.', instructions:['Rest your upper back against the bench.','Place the bar across your hips and brace.','Drive through your heels to lift your hips.','Pause at the top, then lower under control.'] }
];
